language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  skip_cleanup: true
  provider: heroku
  app: app-clicker20
  api_key:
    secure: "31cb1262-0133-47d4-af00-3c0c57ed5731"