language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  skip_cleanup: true
  provider: heroku
  app: app-clicker20
  api_key: 4c33e114-3aae-4ac8-bc75-7d8d401c644c