language: node_js
node_js:
- '10'

before_install:
- npm install -g @angular/cli
install: npm install

branches:
  only:
  - master


deploy:
  skip_cleanup: true
  provider: heroku
  app: app-clicker20
  api_key: e335dc77-431f-47ed-a8ec-2869938cf1f5